/**
 * @file        clang_init.c
 * @brief       _init() function definition, which is not generated by default by Clang with -nostdlib.
 * @author      Kacper Kowalski - kacper.s.kowalski@gmail.com
 */
void _init()
{
}

void _fini()
{

}